<?php

namespace Plugin\SamplePlugin\Repository;

use Plugin\SamplePlugin\Entity\SamplePluginConfig;
use Eccube\Repository\AbstractRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * SamplePluginConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SamplePluginConfigRepository extends AbstractRepository
{
    /**
     * SamplePluginConfigRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, SamplePluginConfig::class);
    }

    // /**
    //  * @param int $id
    //  *
    //  * @return null|SamplePluginConfig
    //  */
    // public function get($id = 1)
    // {
    //     return $this->find($id);
    // }
}
